version: '3.1'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    environment:
      xpack.security.enabled: "false"
    ports:
      - 9200:9200

  kibana:
    image: kibana:5.3.2
    ports:
      - 5601:5601
