eureka:
  client:
    enabled: false

spring:
  application:
    name: jdbc
  main:
    banner-mode: "off"
  datasource:
    url: "jdbc:postgresql://db:5432/app"
    username: dbuser
    password: dbpass

server:
  port: 8000
